In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('crowdedflower.csv', encoding='ISO-8859-1')
df

,_unit_id,relevance,relevance:variance,product_image,product_link,product_price,product_title,query,rank,source,url,product_description
0,711158459,3.67,0.471,http://thumbs2.ebaystatic.com/d/l225/m/mzvzEUI...,http://www.ebay.com/itm/Sony-PlayStation-4-PS4...,$329.98,Sony PlayStation 4 (PS4) (Latest Model)- 500 G...,playstation 4,1,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...
1,711158460,4.00,0.000,http://thumbs3.ebaystatic.com/d/l225/m/mJNDmSy...,http://www.ebay.com/itm/Sony-PlayStation-4-Lat...,$324.84,Sony PlayStation 4 (Latest Model)- 500 GB Jet ...,playstation 4,2,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...
2,711158461,4.00,0.000,http://thumbs4.ebaystatic.com/d/l225/m/m10NZXA...,http://www.ebay.com/itm/Sony-PlayStation-4-PS4...,$324.83,Sony PlayStation 4 PS4 500 GB Jet Black Console,playstation 4,3,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...
3,711158462,3.67,0.471,http://thumbs2.ebaystatic.com/d/l225/m/mZZXTmA...,http://www.ebay.com/itm/Sony-PlayStation-4-500...,$350.00,Sony - PlayStation 4 500GB The Last of Us Rema...,playstation 4,4,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,NaN
4,711158463,3.33,0.471,http://thumbs3.ebaystatic.com/d/l225/m/mzvzEUI...,http://www.ebay.com/itm/Sony-PlayStation-4-PS4...,$308.00\nTrending at\n$319.99,Sony PlayStation 4 (PS4) (Latest Model)- 500 G...,playstation 4,5,eBay,http://www.ebay.com/sch/i.html?_from=R40&_trks...,The PlayStation 4 system opens the door to an ...
...,...,...,...,...,...,...,...,...,...,...,...,...
32666,713196633,NaN,NaN,http://edge.shop.com/ccimg.shop.com/240000/243...,http://www.shop.com/nbts/p1265775653-xinternal...,"$109.99,Sale $74.95",Kamik Gamma2 Snow Boots (For Women),snow boots,30,Shop.com,http://www.shop.com/search/snow boots?k=60&sor...,Closeouts. Perfect for burly winter days where...
32667,713196634,NaN,NaN,http://edge.shop.com/ccimg.shop.com/240000/243...,http://www.shop.com/nbts/p1262233377-xinternal...,$175.00,Hunter Rain Boots - Tour Neoprene,snow boots,31,Shop.com,http://www.shop.com/search/snow boots?k=60&sor...,"Dive into rainy days in these look-great, feel..."
32668,713196635,NaN,NaN,http://edge.shop.com/ccimg.shop.com/240000/243...,http://www.shop.com/nbts/p1265775377-xinternal...,"$175.00,Sale $119.95",Blondo Steffy Snow Boots - Waterproof (For Women),snow boots,32,Shop.com,http://www.shop.com/search/snow boots?k=60&sor...,NaN
32669,713196636,NaN,NaN,http://edge.shop.com/ccimg.shop.com/250000/250...,http://www.shop.com/nbts/p957783018-xinternals...,$169.00,Maine Pac Boots,snow boots,33,Shop.com,http://www.shop.com/search/snow boots?k=60&sor...,Vintage style meets cold weather comfort to cr...
32670,713196637,NaN,NaN,http://edge.shop.com/ccimg.shop.com/240000/243...,http://www.shop.com/nbts/p1237032619-xinternal...,"$59.99,Sale $39.95","Itasca Icebreaker Snow Boots - Waterproof, Ins...",snow boots,34,Shop.com,http://www.shop.com/search/snow boots?k=60&sor...,"A great value in a warm winter boot, Itasca Ic..."

In [4]:
df_test = df[df['query'].isin(['coffee for nespresso',
'rice cooker', 
'nike womens', 
'plantronics corded headset',
'cowboy boots',
'Single serve coffee maker',
'lego star wars',
'flannel sheets',
'batman',
'Phillips coffee maker',
'iphone 4 case', 
'infinity scarf', 
'Cocoa Butter', 
'toddler sandals', 
'yankees',
'fuji bike shirt', 
'car window sticker',
'storage ottoman', 
'an extremely goofy movie',
'portable hard drive',
'long prom dress',
'oakley polarized radar',
'khaki pants', 
'notebook paper', 
'victoria secret pink shorts',
'playstation vita system',
'harley-davidson', 
'reusable straws', 
'glitter vials', 
'flower bulbs',
'coffee cup', 
'pencil skirt',
'nike flip flops', 
'high heels shoes', 
'yankee candle',
'candle lantern', 
'Watch women fossil',
'bike lock', 
'outdoor table cover',
'aveeno shampoo',
"leather men's briefcase",
'Brett Favre NY Titans jersey blue',
'barbie', 
'dual headset splitter',
'macbook case 13 case',
'tote bag', 
'skechers womens shoes',
'seiko monster', 
'stick vacuum', 
'flea and tick control for dogs'])]

In [6]:
df_test = df_test[['_unit_id', 'product_title', 'product_description', 'query', 'relevance']]

In [7]:
df_test

,_unit_id,product_title,product_description,query,relevance
175,711158634,MEN'S NWT VINTAGE REEBOK BRETT FAVRE NEW YORK ...,NaN,Brett Favre NY Titans jersey blue,3.33
176,711158635,Reebok NFL Equipment NY Jets Brett Favre Green...,NaN,Brett Favre NY Titans jersey blue,2.20
177,711158636,Brett Favre New York Titans NFL Equipment Reeb...,NaN,Brett Favre NY Titans jersey blue,3.00
178,711158637,Brett Favre autographed signed NY Titans Throw...,<strong>triplecrownauthentics store</strong>,Brett Favre NY Titans jersey blue,2.67
179,711158638,Brett Favre NY New York Jets Wholesale NFL Foo...,NaN,Brett Favre NY Titans jersey blue,2.67
...,...,...,...,...,...
32657,713196624,AdC raft 30 Cup 110-120V Premium Rice Cooker R...,This premium 30 cup rice cooker cooks and hold...,rice cooker,NaN
32658,713196625,Zojirushi Electric Rice Cooker / Warmer - 10 c...,Zojirushi Electric Rice Cooker / Warmer - 10 c...,rice cooker,NaN
32659,713196626,Proctor Silex 37533 Rice Cooker,Makes 10 cups of cooked rice.Nonstick removabl...,rice cooker,NaN
32660,713196627,Sunpentown SC-889 10 Cup Stainless Steel Rice ...,Easy one-button operation Automatically switch...,rice cooker,NaN
32661,713196628,AdC raft 50 Cup 208V/240V Economy Rice Cooker ...,50 cup heavy duty rice cooker comes with a sta...,rice cooker,NaN

In [9]:
df_test.dropna(subset=['product_title', 'query', 'relevance'], inplace=True)
df_test

<ipython-input-9-35f452331e72>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test.dropna(subset=['product_title', 'query', 'relevance'], inplace=True)

,_unit_id,product_title,product_description,query,relevance
175,711158634,MEN'S NWT VINTAGE REEBOK BRETT FAVRE NEW YORK ...,NaN,Brett Favre NY Titans jersey blue,3.33
176,711158635,Reebok NFL Equipment NY Jets Brett Favre Green...,NaN,Brett Favre NY Titans jersey blue,2.20
177,711158636,Brett Favre New York Titans NFL Equipment Reeb...,NaN,Brett Favre NY Titans jersey blue,3.00
178,711158637,Brett Favre autographed signed NY Titans Throw...,<strong>triplecrownauthentics store</strong>,Brett Favre NY Titans jersey blue,2.67
179,711158638,Brett Favre NY New York Jets Wholesale NFL Foo...,NaN,Brett Favre NY Titans jersey blue,2.67
...,...,...,...,...,...
20370,711178872,Panasonic 10-Cup Rice Cooker / Steamer,NaN,rice cooker,4.00
20371,711178873,Aroma 8-Cup Digital Rice Cooker and Food Steamer,Easily make restaurant-quality white and brown...,rice cooker,3.67
20372,711178874,Tiger 10-Cup Electric Rice Cooker,The Tiger 10-Cup Electric Rice Cooker is capab...,rice cooker,3.67
20373,711178875,Aroma 12-Cup Cool-Touch Digital Egg-Shaped Ric...,About this item\nEnjoy easy home cooking with ...,rice cooker,4.00
20374,711178876,Aroma 14-Cup Rice Cooker,Make perfect rice every time with the Aroma 14...,rice cooker,4.00