## Importação do Pandas

In [1]:
import pandas as pd

## Leitura do Dataset

In [2]:
df = pd.read_csv('wands_negative_subsampling.csv')

## Consulta do Cabeçalho

In [3]:
df.head()

,Unnamed: 0,id,query_id,product_id,label,query,query_class,product_name,product_class,category hierarchy,product_description,product_features,test,val
0,129,129,1,38855,0.5,smart coffee table,Coffee & Cocktail Tables,abheer floor shelf coffee table,Coffee & Cocktail Tables,Furniture / Living Room Furniture / Coffee Tab...,when it comes to rounding out your living ense...,style : modern & contemporary|dswoodtone : med...,0,0
1,130,130,1,9929,1.0,smart coffee table,Coffee & Cocktail Tables,addaly abstract coffee table,Coffee & Cocktail Tables,Furniture / Living Room Furniture / Coffee Tab...,anchor your living room in mid-century style w...,levelofassembly : partial assembly|topcolor : ...,0,0
2,131,131,1,5235,1.0,smart coffee table,Coffee & Cocktail Tables,adoni coffee table,Coffee & Cocktail Tables,Furniture / Living Room Furniture / Coffee Tab...,NaN,dsmetallic : gold|topcolor : clear|dsprimarypr...,0,0
3,132,132,1,26772,0.5,smart coffee table,Coffee & Cocktail Tables,ahart frame coffee table,Coffee & Cocktail Tables,Furniture / Living Room Furniture / Coffee Tab...,your coffee table is a style centerpiece for y...,dsprimaryproductstyle : industrial|style : ind...,0,0
4,133,133,1,3510,0.5,smart coffee table,Coffee & Cocktail Tables,ahern coffee table,Coffee & Cocktail Tables,Furniture / Living Room Furniture / Coffee Tab...,the ahern 4 legs coffee table with storage is ...,topcolor : cherry|topshape : rectangular|topco...,0,0

## Feature Engineering

In [4]:
df = df[['product_id', 'product_name', 'product_description', 'query', 'label', 'test', 'val']]
df

,product_id,product_name,product_description,query,label,test,val
0,38855,abheer floor shelf coffee table,when it comes to rounding out your living ense...,smart coffee table,0.5,0,0
1,9929,addaly abstract coffee table,anchor your living room in mid-century style w...,smart coffee table,1.0,0,0
2,5235,adoni coffee table,NaN,smart coffee table,1.0,0,0
3,26772,ahart frame coffee table,your coffee table is a style centerpiece for y...,smart coffee table,0.5,0,0
4,3510,ahern coffee table,the ahern 4 legs coffee table with storage is ...,smart coffee table,0.5,0,0
...,...,...,...,...,...,...,...
233443,11181,henrika upholstered arm chair dining chair in ...,looking for comfortable dining seating with th...,bubble guppies chair,0.5,1,0
233444,15439,fellsburg linen upholstered parsons chair,NaN,bubble guppies chair,0.5,1,0
233445,451,olin upholstered side chair,if you are looking for a simple yet sleek dini...,bubble guppies chair,0.5,1,0
233446,30764,barbay lounge chair cushion,NaN,bubble guppies chair,0.0,1,0
233447,16796,haings upholstered parsons chair,this set of 2 armless side chairs boasts an up...,bubble guppies chair,0.5,1,0

## Substituição de float('NaN') por String Vazia

In [5]:
df['product_description'] = df['product_description'].replace(float("NaN"), '')

In [6]:
df

,product_id,product_name,product_description,query,label,test,val
0,38855,abheer floor shelf coffee table,when it comes to rounding out your living ense...,smart coffee table,0.5,0,0
1,9929,addaly abstract coffee table,anchor your living room in mid-century style w...,smart coffee table,1.0,0,0
2,5235,adoni coffee table,,smart coffee table,1.0,0,0
3,26772,ahart frame coffee table,your coffee table is a style centerpiece for y...,smart coffee table,0.5,0,0
4,3510,ahern coffee table,the ahern 4 legs coffee table with storage is ...,smart coffee table,0.5,0,0
...,...,...,...,...,...,...,...
233443,11181,henrika upholstered arm chair dining chair in ...,looking for comfortable dining seating with th...,bubble guppies chair,0.5,1,0
233444,15439,fellsburg linen upholstered parsons chair,,bubble guppies chair,0.5,1,0
233445,451,olin upholstered side chair,if you are looking for a simple yet sleek dini...,bubble guppies chair,0.5,1,0
233446,30764,barbay lounge chair cushion,,bubble guppies chair,0.0,1,0
233447,16796,haings upholstered parsons chair,this set of 2 armless side chairs boasts an up...,bubble guppies chair,0.5,1,0

## Divisão do Dataset em Treino, Teste e Validação

In [7]:
df_train = df[(df['test'] == 0) & (df['val'] == 0)]
df_val = df[(df['test'] == 0) & (df['val'] == 1)]
df_test = df[df['test'] == 1]

## Dataset de Treino

In [8]:
df_train = df_train[['product_id', 'product_name', 'product_description', 'query', 'label']]
df_train

,product_id,product_name,product_description,query,label
0,38855,abheer floor shelf coffee table,when it comes to rounding out your living ense...,smart coffee table,0.5
1,9929,addaly abstract coffee table,anchor your living room in mid-century style w...,smart coffee table,1.0
2,5235,adoni coffee table,,smart coffee table,1.0
3,26772,ahart frame coffee table,your coffee table is a style centerpiece for y...,smart coffee table,0.5
4,3510,ahern coffee table,the ahern 4 legs coffee table with storage is ...,smart coffee table,0.5
...,...,...,...,...,...
142319,15439,fellsburg linen upholstered parsons chair,,worn leather office chair,0.5
142320,451,olin upholstered side chair,if you are looking for a simple yet sleek dini...,worn leather office chair,0.5
142321,30764,barbay lounge chair cushion,,worn leather office chair,0.0
142322,16796,haings upholstered parsons chair,this set of 2 armless side chairs boasts an up...,worn leather office chair,0.5
142323,30764,barbay lounge chair cushion,,54 in bench cushion,0.5

## Dataset de Validação

In [9]:
df_val = df_val[['product_id', 'product_name', 'product_description', 'query', 'label']]
df_val

,product_id,product_name,product_description,query,label
142324,4313,"3-tier end table , small book shelf , accent s...",this 3-tier table can be used for many functio...,stoneford end tables white and wood,0.5
142325,32897,aahil end table with storage,streamlined style and a space-conscious design...,stoneford end tables white and wood,0.5
142326,559,abbottsmoor end table,whether every friday is filled with fun family...,stoneford end tables white and wood,0.5
142327,42751,abernethy solid wood end table,"every sofa ’ s favorite sidekick , end tables ...",stoneford end tables white and wood,0.5
142328,1967,adeline end table,whether sidled up beside your sofa or acting a...,stoneford end tables white and wood,0.5
...,...,...,...,...,...
171295,21863,houston toddler bed,the rylee toddler bed helps make the transitio...,upholstered girls bed,0.5
171296,32897,aahil end table with storage,streamlined style and a space-conscious design...,wayfair coffee table,0.5
171297,3871,bordeaux console table,the madison park signature 's bordeaux console...,wayfair coffee table,0.5
171298,13548,raffaello ii rectangular cocktail table,luxury raffaello ii rectangular coffee table c...,wayfair coffee table,0.5
171299,13549,raffaello round cocktail table,the raffaello coffee table set is masterpiece ...,wayfair coffee table,0.5

## Dataset de Teste

In [10]:
df_test = df_test[['product_id', 'product_name', 'product_description', 'query', 'label']]
df_test

,product_id,product_name,product_description,query,label
171300,25434,21.7 '' w waiting room chair with wood frame,"this is a salon chair , barber chair for a hai...",salon chair,1.0
171301,12088,22.5 '' wide polyester side chair,add a beautiful accent to any room with this m...,salon chair,0.0
171302,42931,24.4 '' w metal lounge chair with metal frame,the heavy duty barber chair is built to last ....,salon chair,1.0
171303,2636,25 '' wide faux leather manual swivel standard...,this is a chair designed for your barbershop ....,salon chair,1.0
171304,42923,27.6 '' w antimicrobial leather seat waiting r...,,salon chair,1.0
...,...,...,...,...,...
233443,11181,henrika upholstered arm chair dining chair in ...,looking for comfortable dining seating with th...,bubble guppies chair,0.5
233444,15439,fellsburg linen upholstered parsons chair,,bubble guppies chair,0.5
233445,451,olin upholstered side chair,if you are looking for a simple yet sleek dini...,bubble guppies chair,0.5
233446,30764,barbay lounge chair cushion,,bubble guppies chair,0.0
233447,16796,haings upholstered parsons chair,this set of 2 armless side chairs boasts an up...,bubble guppies chair,0.5

## Exportando para arquivos CSV

In [11]:
df_train.to_csv('df_train_wands.csv', index=False)
df_val.to_csv('df_val_wands.csv', index=False)
df_test.to_csv('df_test_wands.csv', index=False)